// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prafijwpgcsblstfuyba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByYWZpandwZ2NzYmxzdGZ1eWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDI1NTcsImV4cCI6MjA2NjgxODU1N30.YkA6pvtSWEUuoZBwiX5RE6CkUkievfNVSS7Q8UYm4mI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);