// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://xnsxgexzlczqajyihyez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhuc3hnZXh6bGN6cWFqeWloeWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODQwMzIsImV4cCI6MjA2NTI2MDAzMn0.iMfs2R5OrMcLFsCVdGEblsQR9isWIUarlqU4ywtjJso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);